# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Check URL
      uses: urlstechie/urlchecker-action@0.1.9
      with:
        file_types: .json
        retry_count: 3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up GPG
      run: |
        echo "${{ secrets.bot_gpg_pvt }}" > private.key
        gpg --import private.key
        rm private.key
    - name: Config Git
      run: |
        git config --global user.name ${{ secrets.bot_name }}
        git config --global user.email ${{ secrets.bot_email }}
        git config --global user.signingkey ${{ secrets.bot_gpg_id }}
        git config --global push.followTags true
    - name: Black
      run: |
        pip install black
        black generator/main.py
        if ! git diff --no-ext-diff --quiet --exit-code; then
          git add generator/main.py
          git commit -S -a -m "Blackened code"
        fi
    - name: Run
      run: |
        python generator/main.py
        if ! git diff --no-ext-diff --quiet --exit-code; then
          git add .
          git commit -S -a -m "Update"
        fi
    - name: Lint
      uses: avto-dev/markdown-lint@v1.1.0
      continue-on-error: true
      with:
        fix: true
        args: .
    - name: Commit and Push
      run: |
        if ! git diff --no-ext-diff --quiet --exit-code; then
          git add .
          git commit -S -a -m "Update"
          git push
        fi

