# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Check URLs
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: URL
        uses: urlstechie/urlchecker-action@0.1.9
        continue-on-error: true
        with:
          subfolder: sources
          file_types: .json
          retry_count: 3
          cleanup: false
      - name: Black Code Formatter
        uses: lgeiger/black-action@v1.0.1
        with:
          args: .
